version: 0.2

phases:
  build:
    commands:
      - apt-get update -y
      - sudo apt-get install npm -y
      - sudo apt-get install docker.io
      - sudo service docker.io start
      - sudo docker pull nginx

artifacts:
  files:
    - ./*
